# Generated by Django 5.1.2 on 2025-03-14 14:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chief',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('image', models.ImageField(blank=True, null=True, upload_to='chief/')),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=50)),
                ('years_of_experience', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Meals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='meals_image/')),
                ('size', models.CharField(blank=True, max_length=50, null=True)),
                ('preparation_time', models.TimeField()),
                ('description', models.TextField()),
                ('offer', models.CharField(blank=True, max_length=50, null=True)),
                ('tag', models.CharField(choices=[('n', 'New'), ('d', 'Discount'), ('f', 'Feature')], default='n', max_length=50)),
                ('chief', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='meals_chief', to='meals.chief')),
            ],
        ),
    ]
