# Generated by Django 5.1.2 on 2024-12-09 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chief',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='chief/')),
                ('gender', models.BooleanField()),
                ('years_of_experience', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Meals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('image', models.ImageField(upload_to='meals_image/')),
                ('size', models.CharField(max_length=50)),
                ('quantity', models.IntegerField()),
                ('preparation_time', models.DateTimeField()),
                ('desc', models.TextField()),
                ('offer', models.CharField(max_length=50)),
            ],
        ),
    ]
