# Generated by Django 5.1.2 on 2024-12-10 14:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0002_chief_meals'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chief',
            name='meals',
        ),
        migrations.AddField(
            model_name='meals',
            name='chief',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='meals_chief', to='meals.chief'),
        ),
        migrations.AddField(
            model_name='meals',
            name='tag',
            field=models.CharField(choices=[('New', 'New')], default='New', max_length=50),
        ),
    ]
