# Generated by Django 5.1.2 on 2024-12-10 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0003_remove_chief_meals_meals_chief_meals_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chief',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=50),
        ),
    ]
