# Generated by Django 5.1.2 on 2024-12-23 14:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0004_alter_chief_gender'),
        ('restaurant', '0007_alter_restaurant_address_alter_restaurant_desc'),
    ]

    operations = [
        migrations.AddField(
            model_name='meals',
            name='restaurant',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='restaurant.restaurant', verbose_name='meals_restaurant'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='meals',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='meals_image/'),
        ),
        migrations.AlterField(
            model_name='meals',
            name='offer',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='meals',
            name='size',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
