# Generated by Django 5.1.2 on 2024-12-23 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0005_meals_restaurant_alter_meals_image_alter_meals_offer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chief',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='chief/'),
        ),
    ]
