# Generated by Django 5.1.2 on 2025-01-25 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0006_alter_chief_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meals',
            name='preparation_time',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='meals',
            name='tag',
            field=models.CharField(choices=[('n', 'New'), ('d', 'Discount'), ('f', 'Feature')], default='n', max_length=50),
        ),
    ]
