# Generated by Django 5.1.2 on 2025-01-26 19:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0007_alter_meals_preparation_time_alter_meals_tag'),
        ('restaurant', '0008_alter_restaurant_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meals',
            name='restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meals_restaurant', to='restaurant.restaurant'),
        ),
    ]
