# Generated by Django 5.1.2 on 2025-02-16 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_coupon_remove_booking_booking_date_booking_end_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(blank=True, choices=[('active', 'Active'), ('ended', 'Ended'), ('canceled', 'Canceled')], default='active', max_length=50, null=True),
        ),
    ]
