# Generated by Django 5.1.2 on 2025-03-14 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('name', models.CharField(max_length=50)),
                ('image', models.ImageField(blank=True, null=True, upload_to='restaurants/')),
                ('desc', models.TextField(blank=True, max_length=5000)),
                ('address', models.TextField(blank=True, max_length=500)),
                ('phone', models.CharField(blank=True, max_length=50, null=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='restaurant/logo/')),
                ('min_price', models.FloatField(blank=True, null=True)),
                ('tag', models.CharField(choices=[('n', 'New'), ('l', 'Luxury'), ('d', 'Discount')], max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=50, null=True)),
                ('extra_price', models.PositiveIntegerField(blank=True, null=True)),
            ],
        ),
    ]
