# Generated by Django 5.1.2 on 2024-11-08 18:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='')),
                ('name', models.CharField(max_length=50, verbose_name='')),
                ('image', models.ImageField(blank=True, null=True, upload_to='restaurants/', verbose_name='')),
                ('desc', models.TextField(max_length=5000, verbose_name='')),
                ('address', models.TextField(max_length=500, verbose_name='')),
                ('phone', models.IntegerField(max_length=50, verbose_name='')),
                ('logo', models.ImageField(upload_to='restaurant/logo/', verbose_name='')),
                ('min_price', models.FloatField(verbose_name='')),
            ],
        ),
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_type', models.FloatField(verbose_name='')),
                ('number', models.IntegerField(verbose_name='')),
                ('available', models.FloatField(verbose_name='')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurant.restaurant', verbose_name='')),
            ],
        ),
    ]
