# Generated by Django 5.1.2 on 2025-02-14 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0008_alter_restaurant_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='table',
            name='available',
        ),
        migrations.RemoveField(
            model_name='table',
            name='max_people',
        ),
        migrations.RemoveField(
            model_name='table',
            name='number',
        ),
        migrations.RemoveField(
            model_name='table',
            name='table_type',
        ),
        migrations.AddField(
            model_name='table',
            name='extra_price',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='table',
            name='title',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='phone',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
