# Generated by Django 5.1.2 on 2025-02-26 18:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('booking', '0003_alter_booking_status'),
        ('meals', '0008_alter_meals_restaurant'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_completed', models.BooleanField()),
                ('total_after_coupon', models.FloatField()),
                ('total', models.FloatField()),
                ('coupon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_coupon', to='booking.coupon')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MealsDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('price', models.IntegerField()),
                ('total', models.FloatField()),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_detail', to='order.cart')),
                ('meal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_meals', to='meals.meals')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50)),
                ('order_status', models.CharField(max_length=50)),
                ('total_price', models.IntegerField(max_length=50)),
                ('payment_status', models.CharField(max_length=50)),
                ('total_after_coupon', models.FloatField()),
                ('created_at', models.TimeField(auto_now=True)),
                ('delivery_time', models.TimeField()),
                ('delivery_location', models.CharField(max_length=50)),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_cart', to='order.cart')),
                ('coupon_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.coupon')),
                ('meals_detail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meals_detail_order', to='order.mealsdetail')),
            ],
        ),
    ]
