# Generated by Django 5.1.2 on 2025-03-05 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_alter_cart_coupon_alter_mealsdetail_quantity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='cart',
            name='total_after_coupon',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_location',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
