# Generated by Django 5.1.2 on 2025-03-05 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_alter_cart_is_completed_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mealsdetail',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
