# Generated by Django 5.1.2 on 2025-03-05 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_alter_mealsdetail_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mealsdetail',
            name='total',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
